#!/usr/bin/env python3
"""Generate the C++ string table from assets/strings/*.json.

en.json is the reference language. Every other language must have exactly the same keys and the
same {placeholders} per key, and no empty values; otherwise this exits non-zero and the build fails.

Output (written only when the content changes, so builds stay incremental):
  <out>/tonus_strings_gen.hpp   enum class Str, enum class Lang, table declaration
  <out>/tonus_strings_gen.cpp   the table
"""
import argparse
import json
import re
import sys
from pathlib import Path

REFERENCE = "en"
PLACEHOLDER = re.compile(r"\{([a-z_][a-z0-9_]*)\}")


def ident(key: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", key)


def c_literal(s: str) -> str:
    out = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{out}"'


def write_if_changed(path: Path, text: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return
    path.write_text(text, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()

    files = sorted(args.src.glob("*.json"))
    langs = {}
    for f in files:
        with f.open(encoding="utf-8") as fh:
            langs[f.stem] = json.load(fh)
    if REFERENCE not in langs:
        print(f"gen_strings: {REFERENCE}.json missing in {args.src}", file=sys.stderr)
        return 1

    order = [REFERENCE] + sorted(k for k in langs if k != REFERENCE)
    keys = list(langs[REFERENCE].keys())
    errors = []
    for lang in order:
        table = langs[lang]
        for k in keys:
            if k not in table:
                errors.append(f"{lang}: missing key '{k}'")
            elif not str(table[k]).strip():
                errors.append(f"{lang}: empty value for '{k}'")
            elif set(PLACEHOLDER.findall(table[k])) != set(PLACEHOLDER.findall(langs[REFERENCE][k])):
                errors.append(f"{lang}: placeholders differ for '{k}'")
        for k in table:
            if k not in langs[REFERENCE]:
                errors.append(f"{lang}: key '{k}' not in {REFERENCE}.json")
    if errors:
        print("gen_strings: string tables are inconsistent:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 1

    args.out.mkdir(parents=True, exist_ok=True)
    hpp = [
        "// Generated by tools/i18n/gen_strings.py from assets/strings/*.json. Do not edit.",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace tonus::i18n {",
        "",
        "enum class Lang : uint8_t {",
        *[f"    {ident(l)}," for l in order],
        "    Count",
        "};",
        "",
        "enum class Str : uint16_t {",
        *[f"    {ident(k)}," for k in keys],
        "    Count",
        "};",
        "",
        f"inline constexpr const char* kLangCodes[] = {{{', '.join(c_literal(l) for l in order)}}};",
        "extern const char* const kTable[static_cast<int>(Lang::Count)][static_cast<int>(Str::Count)];",
        "",
        "}  // namespace tonus::i18n",
        "",
    ]
    cpp = [
        "// Generated by tools/i18n/gen_strings.py from assets/strings/*.json. Do not edit.",
        '#include "tonus_strings_gen.hpp"',
        "",
        "namespace tonus::i18n {",
        "",
        "const char* const kTable[static_cast<int>(Lang::Count)][static_cast<int>(Str::Count)] = {",
    ]
    for lang in order:
        cpp.append(f"    {{  // {lang}")
        cpp.extend(f"        {c_literal(langs[lang][k])}," for k in keys)
        cpp.append("    },")
    cpp += ["};", "", "}  // namespace tonus::i18n", ""]

    write_if_changed(args.out / "tonus_strings_gen.hpp", "\n".join(hpp))
    write_if_changed(args.out / "tonus_strings_gen.cpp", "\n".join(cpp))
    return 0


if __name__ == "__main__":
    sys.exit(main())
