#pragma once
// Theme tokens (docs/DESIGN_GUIDELINES.md §3). UI code refers to tokens only; theme.cpp is the one
// place that holds hex values.

#include <cstdint>

#include "lvgl.h"

namespace tonus::ui {

enum class ThemeId : uint8_t { Stage, Bedroom, Count };

enum class Token : uint8_t {
    bg,
    bg_grid,
    surface,
    surface_alt,
    titlebar,
    outline,
    text,
    text_dim,
    on_fill,  // text drawn on pastel button fills
    primary,
    pink,
    cyan,
    yellow,
    success,
    early,
    late,
    danger,
    chrome_hi,  // wordmark face, upper half
    chrome_lo,  // wordmark face, lower half
    sparkle,    // brightest highlight
    Count
};

void setTheme(ThemeId id);
ThemeId theme();

uint32_t rgb(Token t);                 // 0xRRGGBB
lv_color_t color(Token t);
lv_color_t lighter(Token t);           // highlight tone for bevels/dashes
lv_color_t darker(Token t);            // bevel tone

// Layout constants from the guidelines.
inline constexpr int kScreenW = 1280;
inline constexpr int kScreenH = 720;
inline constexpr int kArtPx = 4;       // 1 art-px = 4 screen px
inline constexpr int kMinTarget = 96;  // minimum touch target
inline constexpr int kGap = 16;

// Fonts (ui/fonts, generated by tools/fonts/convert.sh).
namespace font {
const lv_font_t* display48();
const lv_font_t* display32();
const lv_font_t* display24();
const lv_font_t* body32();
const lv_font_t* body24();
const lv_font_t* body16();
}  // namespace font

}  // namespace tonus::ui
